MANIFEST_DESC = {
    'well_known_assetlinks': {
        'title': '未找到App Link assetlinks.json文件<br>[android:name=%s]<br>[android:host=%s]',
        'level': 'high',
        'description': '未找到或配置错误的App Link资产验证URL (%s)(状态码：%s)。App Links允许用户从网页URL/电子邮件重定向到移动应用。如果缺少此文件或App Link主机/域配置不正确，恶意应用可以劫持此类URL。这可能导致网络钓鱼攻击，泄露URI中的敏感数据，如个人身份信息、OAuth令牌、密码重置令牌等。你必须通过托管assetlinks.json文件并在Activity意图过滤器中启用[android:autoVerify="true"]来验证App Link域。',
        'name': '未找到App Link assetlinks.json文件 [android:name=%s], [android:host=%s]',
    },
    'clear_text_traffic': {
        'title': '应用启用了明文传输<br>[android:usesCleartextTraffic=true]',
        'level': 'high',
        'description': '应用计划使用明文网络传输，如HTTP、FTP、DownloadManager和MediaPlayer的明文协议。针对API级别27或更低版本的应用，默认值为“true”。API级别28或更高版本的应用默认为“false”。避免明文传输的主要原因是缺乏机密性、真实性和防篡改保护；网络攻击者可以监听传输数据并进行修改，而不会被检测到。',
        'name': '应用启用了明文传输 [android:usesCleartextTraffic=true]',
    },
    'direct_boot_aware': {
        'title': '应用支持直接启动<br>[android:directBootAware=true]',
        'level': 'info',
        'description': '此应用可以在用户解锁设备之前运行。如果你使用了Application的自定义子类，并且应用中的任何组件都支持直接启动，则整个自定义应用都被认为支持直接启动。在直接启动期间，你的应用只能访问存储在设备受保护存储中的数据。',
        'name': '应用支持直接启动 [android:directBootAware=true]',
    },
    'has_network_security': {
        'title': '应用具有网络安全配置<br>[android:networkSecurityConfig=%s]',
        'level': 'info',
        'description': '网络安全配置功能允许应用在不修改应用代码的情况下，通过安全的声明性配置文件自定义其网络安全设置。这些设置可以为特定域和特定应用配置。',
        'name': '应用具有网络安全配置 [android:networkSecurityConfig=%s]',
    },
    'vulnerable_os_version': {
        'title': '应用可安装在存在漏洞的未修补的Android版本上<br>Android %s, [minSdk=%s]',
        'level': 'high',
        'description': '该应用可安装在较旧的Android版本上，这些版本存在多个未修复的漏洞。这些设备不会从Google收到合理的安全更新。支持Android版本 => 10, API 29，以获得合理的安全更新。',
        'name': '应用可安装在存在漏洞的未修补Android版本上 %s, [minSdk=%s]',
    },
    'app_is_debuggable': {
        'title': '应用启用了调试<br>[android:debuggable=true]',
        'level': 'high',
        'description': '应用已启用调试模式，这使得逆向工程师更容易将调试器附加到应用上。这允许转储堆栈跟踪并访问调试助手类。',
        'name': '应用启用了调试 [android:debuggable=true]',
    },
    'app_allowbackup': {
        'title': '应用数据可被备份<br>[android:allowBackup=true]',
        'level': 'warning',
        'description': '此标志允许任何人通过adb备份你的应用数据。它允许已启用USB调试的用户从设备上复制应用数据。',
        'name': '应用数据可被备份 [android:allowBackup=true]',
    },
    'allowbackup_not_set': {
        'title': '应用数据可被备份<br>[android:allowBackup]标志缺失',
        'level': 'warning',
        'description': '应将[android:allowBackup]标志设置为false。默认情况下，它被设置为true，允许任何人通过adb备份你的应用数据。它允许已启用USB调试的用户从设备上复制应用数据。',
        'name': '应用数据可被备份 [android:allowBackup]标志缺失',
    },
    'app_in_test_mode': {
        'title': '应用处于测试模式<br>[android:testOnly=true]',
        'level': 'high',
        'description': '它可能会暴露自身外部的功能或数据，从而导致安全漏洞。',
        'name': '应用处于测试模式 [android:testOnly=true]',
    },
    'task_affinity_set': {
        'title': '活动设置了TaskAffinity<br>(%s)',
        'level': 'warning',
        'description': '如果设置了taskAffinity，则其他应用程序可能读取发送到另一个任务的活动的意图。始终使用默认设置，将关联性保持为包名称，以防止发送或接收的意图中包含的敏感信息被其他应用程序读取。',
        'name': '活动设置了TaskAffinity (%s)',
    },
    'non_standard_launchmode': {
        'title': '活动的启动模式不是标准的。',
        'level': 'warning',
        'description': '活动不应将启动模式属性设置为“singleTask/singleInstance”，因为这将成为根活动，其他应用程序可能会读取调用意图的内容。因此，在意图中包含敏感信息时，需要使用“standard”启动模式属性。',
        'name': '活动的启动模式不是标准的 (%s)。',
    },
    'task_hijacking': {
        'title': '活动(%s)易受Android任务劫持/StrandHogg攻击。',
        'level': 'high',
        'description': '活动不应将启动模式属性设置为“singleTask”。其他应用程序可能会在易受攻击的应用程序的活动堆栈顶部放置恶意活动，导致任务劫持/StrandHogg 1.0漏洞。这使得应用程序成为网络钓鱼攻击的目标。可以通过将启动模式属性设置为“singleInstance”或设置一个空的taskAffinity(taskAffinity =“”)来消除该漏洞。您还可以将应用程序的目标SDK版本(%s)更新到28或更高版本，以在平台级别解决此问题。',
        'name': '活动(%s)易受Android任务劫持/StrandHogg攻击。',
    },
    'task_hijacking2': {
        'title': '活动(%s)易受StrandHogg 2.0攻击。',
        'level': 'high',
        'description': '发现活动易受StrandHogg 2.0任务劫持漏洞的攻击。当易受攻击时，其他应用程序可能会在易受攻击的应用程序的活动堆栈顶部放置恶意活动。这使得应用程序成为网络钓鱼攻击的目标。可以通过将启动模式属性设置为“singleInstance”和设置一个空的taskAffinity(taskAffinity =“”)来消除该漏洞。您还可以将应用程序的目标SDK版本(%s)更新到29或更高版本，以在平台级别解决此问题。',
        'name': '活动(%s)易受StrandHogg 2.0攻击。',
    },
    'improper_provider_permission': {
        'title': '不正确的内容提供程序权限<br>[%s]',
        'level': 'warning',
        'description': '内容提供程序权限设置为允许设备上的任何其他应用访问。内容提供程序可能包含有关应用程序的敏感信息，因此不应共享。',
        'name': '不正确的内容提供程序权限',
    },
    'dialer_code_found': {
        'title': '找到拨号器代码：%s<br>[android:scheme =“android_secret_code”]',
        'level': 'warning',
        'description': '在清单中发现了秘密代码。当输入这些代码到拨号器中时，将授予对可能包含敏感信息的隐藏内容的访问。',
        'name': '找到拨号器代码：%s [android:scheme =“android_secret_code”]',
    },
    'sms_receiver_port_found': {
        'title': '在端口%s上找到数据SMS接收器<br>[android:port]',
        'level': 'warning',
        'description': '二进制SMS接收器配置为监听端口。发送到设备的二进制SMS消息由开发人员选择的方式进行处理。应用程序应适当验证此SMS中的数据。此外，应用程序应假定接收到的SMS来自不受信任的来源。',
        'name': '在端口%s上找到数据SMS接收器 [android:port]',
    },
    'high_intent_priority_found': {
        'title': '高意图优先级(%s)<br>[android:priority]',
        'level': 'warning',
        'description': '通过将意图优先级设置为高于另一个意图，应用程序实际上覆盖了其他请求。',
        'name': '高意图优先级(%s)。[android:priority]',
    },
    'high_action_priority_found': {
        'title': '高操作优先级(%s)<br>[android:priority]',
        'level': 'warning',
        'description': '通过将操作优先级设置为高于其他操作，应用程序实际上覆盖了其他请求。',
        'name': '高操作优先级(%s)。[android:priority]',
    },
    'exported_protected_permission_signature': {
        'title': '<strong>%s</strong>(%s)受权限保护。<br>%s<br>[android:exported = true]',
        'level': 'info',
        'description': '发现%s%s已导出，但受权限保护。',
        'name': '%s %s受权限保护。[%s] [android:exported = true]',
    },
    'exported_protected_permission_normal': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s <br>[android:exported = true]',
        'level': 'warning',
        'description': '发现%s%s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受权限保护。但是，权限的保护级别设置为normal。这意味着恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [android:exported = true]',
    },
    'exported_protected_permission_dangerous': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s <br>[android:exported = true]',
        'level': 'warning',
        'description': '发现%s%s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受权限保护。但是，权限的保护级别设置为dangerous。这意味着恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [android:exported = true]',
    },
    'exported_protected_permission_signatureorsystem': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s <br>[android:exported = true]',
        'level': 'info',
        'description': '发现%s%s已导出，但受权限保护。但是，权限的保护级别设置为signatureOrSystem。建议改用签名级别。对于大多数目的，签名级别应该足够，而且不取决于应用程序在设备上的安装位置。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [android:exported = true]',
    },
    'exported_protected_permission_not_defined': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s <br>[android:exported = true]',
        'level': 'warning',
        'description': '发现%s%s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受权限保护，该权限在分析应用程序时未定义。因此，应检查权限的保护级别。如果将其设置为normal或dangerous，则恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [android:exported = true]',
    },
    'exported_protected_permission_normal_app_level': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[android:exported=true]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限保护。但是，权限的保护级别设置为normal。这意味着恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [android:exported=true]',
    },
    'exported_protected_permission_dangerous_app_level': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[android:exported=true]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限保护。但是，权限的保护级别设置为dangerous。这意味着恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [android:exported=true]',
    },
    'exported_protected_permission': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护。<br>%s<br>[android:exported=true]',
        'level': 'info',
        'description': '发现%s %s已导出，但在应用程序级别受权限保护。',
        'name': '%s %s在应用程序级别受权限保护。[%s] [android:exported=true]',
    },
    'exported_protected_permission_signatureorsystem_app_level': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[android:exported=true]',
        'level': 'info',
        'description': '发现%s %s已导出，但在应用程序级别受权限保护。但是，权限的保护级别设置为signatureOrSystem。建议改用签名级别。对于大多数目的，签名级别应该足够，而且不取决于应用程序在设备上的安装位置。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [android:exported=true]',
    },
    'exported_protected_permission_app_level': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[android:exported=true]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限保护，该权限在分析应用程序时未定义。因此，应检查权限的保护级别。如果将其设置为normal或dangerous，则恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [android:exported=true]',
    },
    'explicitly_exported': {
        'title': '<strong>%s</strong>(%s)未受保护。<br>[android:exported=true]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。',
        'name': '%s %s未受保护。[android:exported=true]',
    },
    'exported_intent_filter_exists': {
        'title': '<strong>%s</strong>(%s)未受保护。<br>存在意图过滤器。',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。意图过滤器的存在表明%s显式导出。',
        'name': '%s %s未受保护。意图过滤器存在。',
    },
    'exported_provider': {
        'title': '<strong>%s</strong>(%s)未受保护。<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它是一个内容提供者，针对的API级别低于17，使其默认导出，无论系统的API级别如何。',
        'name': '%s %s未受保护。[内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_2': {
        'title': '<strong>%s</strong>(%s)在运行在API级别低于17的设备上时不会受到保护。<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'warning',
        'description': '如果应用程序运行在API级别低于17的设备上，内容提供者(%s %s)将被导出。在这种情况下，它会与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。',
        'name': '%s %s在运行在API级别低于17的设备上时不会受到保护。[内容提供者，targetSdkVersion >= 17]',
    },
    'exported_provider_normal': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受权限保护。但是，权限的保护级别设置为normal。这意味着恶意应用程序可以请求和获得权限并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获得权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_danger': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受到权限的保护。然而，权限的保护级别设置为dangerous。这意味着恶意应用程序可以请求并获取该权限，并与组件交互。如果它设置为signature，只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_signature': {
        'title': '<strong>%s</strong>(%s)受权限保护。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'info',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受到权限的保护。',
        'name': '%s %s受权限保护。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_signatureorsystem': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'info',
        'description': '发现%s %s已导出，但受到应用程序级别的权限保护。但是，权限的保护级别设置为signatureOrSystem。建议改用签名级别。签名级别应足以满足大多数目的，且不依赖于应用程序在设备上的安装位置。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_unknown': {
        'title': '<strong>%s</strong>(%s)受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它受到一个在分析应用中未定义的权限的保护。因此，应在权限定义的位置检查权限的保护级别。如果设置为normal或dangerous，恶意应用程序可以请求并获取权限，并与组件交互。如果设置为signature，只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_normal_app': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限保护。但是，权限的保护级别设置为normal。这意味着恶意应用程序可以请求并获取权限，并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_danger_appl': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限保护。但是，权限的保护级别设置为dangerous。这意味着恶意应用程序可以请求并获取权限，并与组件交互。如果将其设置为signature，则只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_signature_appl': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'info',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到权限的保护。',
        'name': '%s %s在应用程序级别受权限保护。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_signatureorsystem_app': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'info',
        'description': '发现%s %s已导出，但在应用程序级别受权限保护。但是，权限的保护级别设置为signatureOrSystem。建议改用签名级别。签名级别应足以满足大多数目的，且不依赖于应用程序在设备上的安装位置。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
    'exported_provider_unknown_app': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion < 17]',
        'level': 'warning',
        'description': '发现%s %s与设备上的其他应用共享，因此可以被设备上的任何其他应用访问。它在应用程序级别受到一个未在分析应用中定义的权限的保护。因此，应在权限定义的位置检查权限的保护级别。如果设置为normal或dangerous，恶意应用程序可以请求并获取权限，并与组件交互。如果设置为signature，则只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion < 17]',
    },
   'exported_provider_normal_app_new': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'warning',
        'description': '如果应用程序在API级别低于17的设备上运行，内容提供者(%s)将会被导出。在这种情况下，它仍将受到权限的保护。然而，权限的保护级别设置为normal。这意味着恶意应用程序可以请求并获取权限，并与组件交互。如果设置为signature，只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion >= 17]',
    },
    'exported_provider_danger_app_new': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'warning',
        'description': '如果应用程序在API级别低于17的设备上运行，内容提供者(%s)将会被导出。在这种情况下，它仍将受到权限的保护。但是，权限的保护级别设置为dangerous。这意味着恶意应用程序可以请求并获取权限，并与组件交互。如果设置为signature，只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion >= 17]',
    },
    'exported_provider_signature_app_new': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护。<br>%s<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'info',
        'description': '如果应用程序在API级别低于17的设备上运行，内容提供者(%s)将会被导出。尽管如此，它受到权限的保护。',
        'name': '%s %s在应用程序级别受权限保护。[%s] [内容提供者，targetSdkVersion >= 17]',
    },
    'exported_provider_signatureorsystem_app_new': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'info',
        'description': '如果应用程序在API级别低于17的设备上运行，内容提供者(%s)将会被导出。在这种情况下，它仍将受到权限的保护。然而，权限的保护级别设置为signatureOrSystem。建议使用签名级别。签名级别应足以满足大多数目的，且不依赖于应用程序在设备上的安装位置。',
        'name': '%s %s在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion >= 17]',
    },
    'exported_provider_unknown_app_new': {
        'title': '<strong>%s</strong>(%s)在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。<br>%s<br>[内容提供者，targetSdkVersion >= 17]',
        'level': 'warning',
        'description': '如果应用程序在API级别低于17的设备上运行，内容提供者(%s)将会被导出。在这种情况下，它仍将受到一个在分析应用中未定义的权限的保护。因此，应在权限定义的位置检查权限的保护级别。如果设置为normal或dangerous，恶意应用程序可以请求并获取权限，并与组件交互。如果设置为signature，则只有使用相同证书签名的应用程序才能获取权限。',
        'name': '%s %s在应用程序级别受权限保护，但如果应用程序在API级别低于17的设备上运行，则应检查权限的保护级别。[%s] [内容提供者，targetSdkVersion >= 17]',
    },
}
