
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml

# This list is also updated periodically with scripts/update_android_permissions.py
# ######################################### PERMISSIONS ###################
# flake8: noqa
DVM_PERMISSIONS = {
    'MANIFEST_PERMISSION': {
        'SEND_SMS': ['dangerous', '发送短信', '允许应用发送短信。恶意应用可能会在未经您确认的情况下发送消息，从而导致您的损失。'],
        'SEND_SMS_NO_CONFIRMATION': ['dangerous', '直接发送短信', '通过消息应用直接发送短信，无需用户输入或确认。'],
        'CALL_PHONE': ['dangerous', '直接拨打电话号码', '允许应用在不经过您干预的情况下拨打电话号码。恶意应用可能会导致您的电话账单出现意外通话费用。请注意，此权限不允许应用拨打紧急电话号码。'],
        'RECEIVE_SMS': ['dangerous', '接收短信', '允许应用接收和处理短信。恶意应用可能会监控您的短信或在不向您显示的情况下删除它们。'],
        'RECEIVE_MMS': ['dangerous', '接收彩信', '允许应用接收和处理彩信。恶意应用可能会监控您的信息或在不向您显示的情况下删除它们。'],
        'READ_SMS': ['dangerous', '读取短信或彩信', '允许应用读取存储在您手机或SIM卡上的短信。恶意应用可能读取您的机密信息。'],
        'WRITE_SMS': ['dangerous', '编辑短信或彩信', '允许应用修改存储在您手机或SIM卡上的短信。恶意应用可能删除您的消息。'],
        'RECEIVE_WAP_PUSH': ['dangerous', '接收WAP推送消息', '允许应用接收和处理WAP推送消息。恶意应用可能会监控您的消息或在不向您显示的情况下删除它们。'],
        'READ_CONTACTS': ['dangerous', '读取联系人数据', '允许应用读取存储在您手机上的所有联系人(地址)数据。恶意应用可以利用此数据将您的信息发送给其他人。'],
        'WRITE_CONTACTS': ['dangerous', '写入联系人数据', '允许应用修改存储在您手机上的联系人(地址)数据。恶意应用可以利用此数据删除或修改您的联系人数据。'],
        'READ_PROFILE': ['dangerous', '读取用户的个人资料数据', '允许应用读取用户的个人资料数据。'],
        'WRITE_PROFILE': ['dangerous', '写入用户的个人资料数据', '允许应用写入(但不读取)用户的个人资料数据。'],
        'READ_SOCIAL_STREAM': ['dangerous', '从用户的社交流中读取', '允许应用从用户的社交流中读取数据。'],
        'WRITE_SOCIAL_STREAM': ['dangerous', '写入用户的社交流数据', '允许应用写入(但不读取)用户的社交流数据。'],
        'READ_CALENDAR': ['dangerous', '读取日历事件', '允许应用读取存储在您手机上的所有日历事件。恶意应用可以利用此数据将您的日历事件发送给其他人。'],
        'WRITE_CALENDAR': ['dangerous', '添加或修改日历事件并发送电子邮件给嘉宾', '允许应用添加或更改您的日历上的事件，可能会向嘉宾发送电子邮件。恶意应用可以利用此权限删除或修改您的日历事件或向嘉宾发送电子邮件。'],
        'READ_USER_DICTIONARY': ['dangerous', '读取用户定义的字典', '允许应用读取用户可能存储在用户字典中的任何私人词汇、姓名和短语。'],
        'WRITE_USER_DICTIONARY': ['normal', '写入用户定义的字典', '允许应用将新词汇写入用户字典。'],
        'READ_HISTORY_BOOKMARKS': ['dangerous', '读取浏览器的历史记录和书签', '允许应用读取浏览器访问过的所有URL和所有浏览器书签。'],
        'WRITE_HISTORY_BOOKMARKS': ['dangerous', '写入浏览器的历史记录和书签', '允许应用修改存储在您手机上的浏览器历史记录或书签。恶意应用可以利用此权限删除或修改您的浏览器数据。'],
        'SET_ALARM': ['normal', '在闹钟应用中设置闹钟', '允许应用在安装的闹钟应用中设置闹钟。某些闹钟应用可能不实现此功能。'],
        'ACCESS_FINE_LOCATION': ['dangerous', '精确位置(GPS)', '访问精确位置来源，例如手机上的全球定位系统。恶意应用可以利用此权限确定您的位置，并可能消耗更多电池电量。'],
        'ACCESS_COARSE_LOCATION': ['dangerous', '粗略位置(基于网络)', '访问粗略位置来源，例如移动网络数据库，以确定大致的手机位置。恶意应用可以利用此权限大致确定您的位置。'],
        'ACCESS_MOCK_LOCATION': ['dangerous', '模拟位置来源进行测试', '创建模拟位置来源进行测试。恶意应用可以利用此权限覆盖由真实位置来源(如GPS或网络提供商)返回的位置和/或状态。'],
        'ACCESS_LOCATION_EXTRA_COMMANDS': ['normal', '访问额外的位置提供商命令', '访问额外的位置提供商命令。恶意应用可以利用此权限干扰GPS或其他位置来源的操作。'],
        'INSTALL_LOCATION_PROVIDER': ['signatureOrSystem', '安装位置提供商的权限', '创建模拟位置来源进行测试。恶意应用可以利用此权限覆盖由真实位置来源(如GPS或网络提供商)返回的位置和/或状态，或监视并向外部来源报告您的位置。'],
        'INTERNET': ['normal', '完全的互联网访问', '允许应用创建网络套接字。'],
        'ACCESS_NETWORK_STATE': ['normal', '查看网络状态', '允许应用查看所有网络状态。'],
        'ACCESS_WIFI_STATE': ['normal', '查看Wi-Fi状态', '允许应用查看Wi-Fi状态的信息。'],
        'BLUETOOTH': ['normal', '创建蓝牙连接', '允许应用连接到配对的蓝牙设备。'],
        'NFC': ['normal', '控制近场通信', '允许应用与近场通信(NFC)标签、卡片和读卡器通信。'],
        'USE_SIP': ['dangerous', '进行/接收互联网电话', '允许应用使用SIP服务进行/接收互联网电话。'],
        'ACCOUNT_MANAGER': ['signature', '作为帐户管理器服务', '允许应用对帐户身份验证器发起呼叫。'],
        'GET_ACCOUNTS': ['dangerous', '列出账户', '允许访问账户服务中的账户列表。'],
        'AUTHENTICATE_ACCOUNTS': ['dangerous', '作为账户验证器', '允许应用使用账户管理器的账户验证器功能，包括创建账户以及获取和设置它们的密码。'],
        'USE_CREDENTIALS': ['dangerous', '使用认证凭证', '允许应用请求认证令牌。'],
        'MANAGE_ACCOUNTS': ['dangerous', '管理账户列表', '允许应用执行操作，如添加和删除账户以及删除其密码。'],
        'MODIFY_AUDIO_SETTINGS': ['normal', '更改您的音频设置', '允许应用修改全局音频设置，如音量和路由。'],
        'RECORD_AUDIO': ['dangerous', '录音', '允许应用访问音频记录路径。'],
        'CAMERA': ['dangerous', '拍摄照片和视频', '允许应用使用相机拍摄照片和视频。这使得应用能够随时收集相机看到的图像。'],
        'VIBRATE': ['normal', '控制振动器', '允许应用控制振动器。'],
        'FLASHLIGHT': ['normal', '控制手电筒', '允许应用控制手电筒。'],
        'ACCESS_USB': ['signatureOrSystem', '访问USB设备', '允许应用访问USB设备。'],
        'HARDWARE_TEST': ['signature', '硬件测试', '允许应用控制各种外围设备以进行硬件测试。'],
        'PROCESS_OUTGOING_CALLS': ['dangerous', '拦截外拨电话', '允许应用处理外拨电话并更改要拨打的号码。恶意应用可能监视、重定向或阻止外拨电话。'],
        'MODIFY_PHONE_STATE': ['signatureOrSystem', '修改电话状态', '允许应用控制设备的电话功能。应用可以切换网络、打开和关闭电话无线电等，而无需通知您。'],
        'READ_PHONE_STATE': ['dangerous', '读取电话状态和身份', '允许应用访问设备的电话功能。应用可以确定这部电话的电话号码和序列号、是否有活跃的电话、该电话连接的号码等。'],
        'WRITE_EXTERNAL_STORAGE': ['dangerous', '读/写/删除外部存储内容', '允许应用写入外部存储。'],
        'READ_EXTERNAL_STORAGE': ['dangerous', '读取外部存储内容', '允许应用从外部存储读取。'],
        'WRITE_SETTINGS': ['dangerous', '修改全局系统设置', '允许应用修改系统的设置数据。恶意应用可以破坏您的系统配置。'],
        'WRITE_SECURE_SETTINGS': ['signatureOrSystem', '修改安全系统设置', '允许应用修改系统的安全设置数据。不适用于普通应用。'],
        'WRITE_GSERVICES': ['signatureOrSystem', '修改Google服务映射', '允许应用修改Google服务映射。不适用于普通应用。'],
        'EXPAND_STATUS_BAR': ['normal', '展开/收起状态栏', '允许应用展开或收起状态栏。'],
        'GET_TASKS': ['dangerous', '检索运行中的应用', '允许应用检索有关当前和最近运行任务的信息。恶意应用可能利用此功能发现有关其他应用的私密信息。'],
        'REORDER_TASKS': ['normal', '重新排序运行中的应用', '允许应用将任务移至前台和后台。恶意应用可以在未经您控制的情况下强行置于前台。'],
        'CHANGE_CONFIGURATION': ['signatureOrSystem', '更改您的UI设置', '允许应用更改当前配置，例如区域设置或整体字体大小。'],
        'RESTART_PACKAGES': ['normal', '终止背景进程', '允许应用终止其他应用的背景进程，即使内存不低。'],
        'KILL_BACKGROUND_PROCESSES': ['normal', '终止背景进程', '允许应用终止其他应用的背景进程，即使内存不低。'],
        'FORCE_STOP_PACKAGES': ['signature', '强制停止其他应用', '允许应用强制停止其他应用。'],
        'DUMP': ['signatureOrSystem', '检索系统内部状态', '允许应用检索系统的内部状态。恶意应用可能检索各种私密和安全信息，通常不应需要这些信息。'],
        'SYSTEM_ALERT_WINDOW': ['dangerous', '显示系统级警告', '允许应用显示系统警告窗口。恶意应用可以控制手机的整个屏幕。'],
        'SET_ANIMATION_SCALE': ['dangerous', '修改全局动画速度', '允许应用在任何时候更改全球动画速度(更快或更慢的动画)。'],
        'PERSISTENT_ACTIVITY': ['dangerous', '使应用始终运行', '允许应用使其部分内容持久化，使系统无法将其用于其他应用。'],
        'GET_PACKAGE_SIZE': ['normal', '测量应用存储空间', '允许应用找出任何包使用的空间。'],
        'SET_PREFERRED_APPLICATIONS': ['signature', '设置首选应用', '允许应用修改您的首选应用。这可以允许恶意应用在不被察觉的情况下更改运行的应用，冒充您现有的应用以收集私人数据。'],
        'RECEIVE_BOOT_COMPLETED': ['normal', '自动启动', '允许应用在系统启动完成后立即启动自身。这可能使电话启动变慢，让应用通过始终运行减慢电话的总体速度。'],
        'BROADCAST_STICKY': ['normal', '发送粘性广播', '允许应用发送粘性广播，这些广播在广播结束后仍存在。恶意应用可以通过使电话使用过多内存使电话变慢或不稳定。'],
        'WAKE_LOCK': ['normal', '防止手机休眠', '允许应用防止手机进入休眠状态。'],
        'SET_WALLPAPER': ['normal', '设置壁纸', '允许应用设置系统壁纸。'],
        'SET_WALLPAPER_HINTS': ['normal', '设置壁纸尺寸提示', '允许应用设置系统壁纸尺寸提示。'],
        'SET_TIME': ['signatureOrSystem', '设置时间', '允许应用更改手机的时钟时间。'],
        'SET_TIME_ZONE': ['signatureOrSystem', '设置时区', '允许应用更改手机的时区。'],
        'MOUNT_UNMOUNT_FILESYSTEMS': ['dangerous', '挂载和卸载文件系统', '允许应用为可移动存储挂载和卸载文件系统。'],
        'MOUNT_FORMAT_FILESYSTEMS': ['dangerous', '格式化外部存储', '允许应用格式化可移动存储。'],
        'ASEC_ACCESS': ['signature', '获取内部存储信息', '允许应用获取内部存储信息。'],
        'ASEC_CREATE': ['signature', '创建内部存储', '允许应用创建内部存储。'],
        'ASEC_DESTROY': ['signature', '销毁内部存储', '允许应用销毁内部存储。'],
        'ASEC_MOUNT_UNMOUNT': ['signature', '挂载/卸载内部存储', '允许应用挂载或卸载内部存储。'],
        'ASEC_RENAME': ['signature', '重命名内部存储', '允许应用重命名内部存储。'],
        'DISABLE_KEYGUARD': ['normal', '禁用键盘锁', '允许应用在不安全的情况下禁用键盘锁。'],
        'READ_SYNC_SETTINGS': ['normal', '读取同步设置', '允许应用读取同步设置，例如是否为联系人启用同步。'],
        'WRITE_SYNC_SETTINGS': ['normal', '写入同步设置', '允许应用修改同步设置，例如是否为联系人启用同步。'],
        'READ_SYNC_STATS': ['normal', '读取同步统计', '允许应用读取同步统计信息，例如已发生的同步历史。'],
        'WRITE_APN_SETTINGS': ['dangerous', '写入接入点名称设置', '允许应用修改APN设置，如任何APN的代理和端口。'],
        'SUBSCRIBED_FEEDS_READ': ['normal', '读取订阅的供稿', '允许应用接收当前同步供稿的详细信息。'],
        'SUBSCRIBED_FEEDS_WRITE': ['dangerous', '写入订阅的供稿', '允许应用修改您当前同步的供稿。恶意应用可能会更改您的同步供稿。'],
        'CHANGE_NETWORK_STATE': ['normal', '更改网络连接状态', '允许应用更改网络连接状态。'],
        'CHANGE_WIFI_STATE': ['normal', '更改Wi-Fi状态', '允许应用连接到Wi-Fi接入点并断开连接，以及对配置的Wi-Fi网络进行更改。'],
        'CHANGE_WIFI_MULTICAST_STATE': ['normal', '允许Wi-Fi多播接收', '允许应用接收未直接地址到您设备的数据包。这在发现附近提供的服务时可能有用。它比非多播模式使用更多的电力。'],
        'BLUETOOTH_ADMIN': ['normal', '蓝牙管理', '允许应用发现和配对蓝牙设备。'],
        'CLEAR_APP_CACHE': ['signatureOrSystem', '删除所有应用缓存数据', '允许应用通过删除应用缓存目录中的文件释放手机存储空间。通常非常限制系统进程的访问。'],
        'READ_LOGS': ['dangerous', '读取敏感日志数据', '允许应用读取系统的各种日志文件。这使它能够发现您与手机互动的一般信息，可能包括个人或私人信息。'],
        'SET_DEBUG_APP': ['dangerous', '启用应用调试', '允许应用为另一应用开启调试。恶意应用可以利用此功能杀死其他应用。'],
        'SET_PROCESS_LIMIT': ['dangerous', '限制运行中的进程数量', '允许应用控制将运行的最大进程数。普通应用不需要此权限。'],
        'SET_ALWAYS_FINISH': ['dangerous', '使所有背景应用关闭', '允许应用控制活动是否总是在进入背景后立即完成。普通应用不需要此权限。'],
        'SIGNAL_PERSISTENT_PROCESSES': ['dangerous', '向应用发送Linux信号', '允许应用请求将所提供的信号发送到所有持久进程。'],
        'DIAGNOSTIC': ['signature', '读/写诊断资源', '允许应用读写诊断组拥有的任何资源，例如/dev中的文件。这可能会影响系统稳定性和安全性。此权限仅应由制造商或运营商用于硬件特定的诊断。'],
        'STATUS_BAR': ['signatureOrSystem', '禁用或修改状态栏', '允许应用禁用状态栏或添加和删除系统图标。'],
        'STATUS_BAR_SERVICE': ['signature', '状态栏', '允许应用成为状态栏。'],
        'FORCE_BACK': ['signature', '强制应用关闭', '允许应用强制任何处于前台的活动关闭并返回。普通应用不需要此权限。'],
        'UPDATE_DEVICE_STATS': ['signatureOrSystem', '修改电池统计数据', '允许修改收集的电池统计数据。普通应用不适用。'],
        'INTERNAL_SYSTEM_WINDOW': ['signature', '显示未授权窗口', '允许创建预期由内部系统用户界面使用的窗口。普通应用不适用。'],
        'MANAGE_APP_TOKENS': ['signature', '管理应用令牌', '允许应用创建并管理自己的令牌，绕过它们的常规Z排序。普通应用不需要此权限。'],
        'INJECT_EVENTS': ['signature', '按键和控制按钮', '允许应用向其他应用传递其自己的输入事件(按键等)。恶意应用可以使用此功能接管手机。'],
        'SET_ACTIVITY_WATCHER': ['signature', '监控和控制所有应用的启动', '允许应用监控和控制系统如何启动活动。恶意应用可能完全危害系统。此权限仅用于开发，不适用于常规手机使用。'],
        'SHUTDOWN': ['signature', '部分关闭', '使活动管理器进入关闭状态。不执行完全关闭。'],
        'STOP_APP_SWITCHES': ['signature', '阻止应用切换', '阻止用户切换到另一个应用。'],
        'READ_INPUT_STATE': ['signature', '记录您输入的内容和您的操作', '允许应用观察您在与另一应用交互时按下的键(如输入密码)。普通应用不需要此权限。'],
        'BIND_INPUT_METHOD': ['signature', '绑定到输入法', '允许持有者绑定到输入法的顶级接口。普通应用不需要此权限。'],
        'BIND_WALLPAPER': ['signatureOrSystem', '绑定到壁纸', '允许持有者绑定到壁纸的顶级接口。普通应用不需要此权限。'],
        'BIND_DEVICE_ADMIN': ['signature', '与设备管理员互动', '允许持有者向设备管理员发送意图。普通应用不需要此权限。'],
        'SET_ORIENTATION': ['signature', '更改屏幕方向', '允许应用随时更改屏幕旋转。普通应用不需要此权限。'],
        'INSTALL_PACKAGES': ['signatureOrSystem', '直接安装应用', '允许应用安装新的或更新的Android包。恶意应用可以利用此功能添加具有任意强大权限的新应用。'],
        'REQUEST_INSTALL_PACKAGES': ['dangerous', '请求安装包', '允许应用请求安装包。恶意应用可以利用此功能试图诱导用户安装额外的恶意包。'],
        'CLEAR_APP_USER_DATA': ['signature', '删除其他应用的数据', '允许应用清除用户数据。'],
        'DELETE_CACHE_FILES': ['signatureOrSystem', '删除其他应用的缓存', '允许应用删除缓存文件。'],
        'DELETE_PACKAGES': ['signatureOrSystem', '删除应用', '允许应用删除Android包。恶意应用可能使用此权限删除重要应用。'],
        'MOVE_PACKAGE': ['signatureOrSystem', '移动应用资源', '允许应用将应用资源从内部媒体移动到外部媒体，反之亦然。'],
        'CHANGE_COMPONENT_ENABLED_STATE': ['signatureOrSystem', '启用或禁用应用组件', '允许应用更改其他应用的组件是否启用。恶意应用可能利用此功能禁用重要的手机功能。在使用此权限时需要格外小心，因为可能会使应用组件进入无法使用、不一致或不稳定的状态。'],
        'ACCESS_SURFACE_FLINGER': ['signature', '访问SurfaceFlinger', '允许应用使用SurfaceFlinger的低级特性。'],
        'READ_FRAME_BUFFER': ['signature', '读取帧缓冲区', '允许应用读取帧缓冲区的内容。'],
        'BRICK': ['signature', '永久禁用手机', '允许应用永久禁用整个手机。这非常危险。'],
        'REBOOT': ['signatureOrSystem', '强制手机重启', '允许应用强制手机重启。'],
        'DEVICE_POWER': ['signature', '开关手机', '允许应用开启或关闭手机。'],
        'FACTORY_TEST': ['signature', '以工厂测试模式运行', '以低级制造商测试运行，允许完全访问手机硬件。仅当手机处于制造商测试模式时可用。'],
        'BROADCAST_PACKAGE_REMOVED': ['signature', '发送应用被移除的广播', '允许应用广播通知，告知某个应用包已被移除。恶意应用可能利用此功能终止任何其他正在运行的应用。'],
        'BROADCAST_SMS': ['signature', '发送短信接收广播', '允许应用广播通知，告知短信消息已被接收。恶意应用可能使用此功能伪造收到的短信。'],
        'BROADCAST_WAP_PUSH': ['signature', '发送WAP-PUSH接收广播', '允许应用广播通知，告知WAP-PUSH消息已被接收。恶意应用可能利用此功能伪造MMS消息接收或悄无声息地用恶意变体替换任何网页的内容。'],
        'MASTER_CLEAR': ['signatureOrSystem', '重置系统到出厂设置', '允许应用完全重置系统到其出厂设置，擦除所有数据、配置和已安装的应用。'],
        'CALL_PRIVILEGED': ['signatureOrSystem', '直接拨打任何电话号码', '允许应用直接拨打任何电话号码，包括紧急号码，无需您的介入。恶意应用可能进行不必要且非法的紧急服务电话。'],
        'PERFORM_CDMA_PROVISIONING': ['signatureOrSystem', '直接开始CDMA手机设置', '允许应用开始CDMA供应。恶意应用可能不必要地开始CDMA供应。'],
        'CONTROL_LOCATION_UPDATES': ['signatureOrSystem', '控制位置更新通知', '允许启用/禁用来自无线电的位置更新通知。普通应用不应使用此权限。'],
        'ACCESS_CHECKIN_PROPERTIES': ['signatureOrSystem', '访问签到属性', '允许读写由签到服务上传的属性。普通应用不应使用此权限。'],
        'PACKAGE_USAGE_STATS': ['signature', '更新组件使用统计', '允许修改收集的组件使用统计。普通应用不应使用此权限。'],
        'BATTERY_STATS': ['signature', '修改电池统计', '允许修改收集的电池统计数据。普通应用不应使用此权限。'],
        'BACKUP': ['signatureOrSystem', '控制系统备份和恢复', '允许应用控制系统的备份和恢复机制。普通应用不应使用此权限。'],
        'BIND_APPWIDGET': ['signatureOrSystem', '选择小部件', '允许应用告诉系统哪些小部件可以被哪个应用使用。有了这个权限，应用可以将个人数据访问权限授予其他应用。普通应用不应使用此权限。'],
        'CHANGE_BACKGROUND_DATA_SETTING': ['signature', '更改后台数据使用设置', '允许应用更改后台数据使用设置。'],
        # Short descriptions are generated by ChatGPT, so they may not be accurate.
        'GLOBAL_SEARCH': ['signatureOrSystem', "允许全局搜索系统访问提供者的数据。", '此权限可用于内容提供者，允许全局搜索系统访问其数据。通常在提供者有某些权限保护(全局搜索不会持有这些权限)时使用，添加为提供者路径中的只读权限，供全局搜索查询使用。此权限不能由常规应用持有；它用于保护自己免受除全局搜索之外的任何其他人访问。'],
        'GLOBAL_SEARCH_CONTROL': ['signature', '无指定角色或功能的权限。', '无指定角色或功能的权限。'],
        'SET_WALLPAPER_COMPONENT': ['signatureOrSystem', '允许设置壁纸组件。', '允许设置壁纸组件。'],
        'ACCESS_CACHE_FILESYSTEM': ['signatureOrSystem', '访问缓存文件系统。', '允许应用读取和写入缓存文件系统。'],
        'COPY_PROTECTED_DATA': ['signature', '允许调用默认容器服务复制内容。不可供普通应用使用。', '允许调用默认容器服务复制内容。不可供普通应用使用。'],
        'C2D_MESSAGE': ['signature', '允许云到设备消息。', '允许应用接收推送通知。'],
        'ADD_VOICEMAIL': ['dangerous', '添加语音邮件到系统中。', '允许应用将语音邮件添加到系统中。'],
        'ACCEPT_HANDOVER': ['dangerous', '使调用应用能够继续另一个应用中开始的通话。', '允许调用应用继续另一个应用中开始的通话。例如，一个视频通话应用希望继续用户的语音通话。'],
        'ACCESS_NOTIFICATION_POLICY': ['normal', '用于访问通知策略的标记权限。', '应用需要此权限才能访问通知策略。'],
        'ANSWER_PHONE_CALLS': ['dangerous', '允许应用接听来电。', '允许应用接听来电。'],
        'BIND_ACCESSIBILITY_SERVICE': ['signature', '由辅助服务系统绑定所需。', '必须由辅助服务(AccessibilityService)要求，以确保只有系统可以绑定到它。'],
        'BIND_AUTOFILL_SERVICE': ['signature', '由自动填充服务系统绑定所需。', '必须由自动填充服务(AutofillService)要求，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_SERVICE': ['signature', '系统绑定到运营商消息服务所需的权限。', '允许系统进程绑定到运营商应用中的服务。运营商应用应使用此权限保护只有系统允许绑定的服务。'],
        'BIND_CARRIER_SERVICES': ['signature', '系统绑定到运营商服务所需的权限。', '允许系统进程绑定到运营商应用中的服务。运营商应用应使用此权限保护只有系统允许绑定的服务。'],
        'BIND_CHOOSER_TARGET_SERVICE': ['signature', '由ChooserTargetServices系统绑定所需。', '必须由ChooserTargetService要求，以确保只有系统可以绑定到它。'],
        'BIND_CONDITION_PROVIDER_SERVICE': ['signature', '由ConditionProviderServices系统绑定所需。', '必须由ConditionProviderService要求，以确保只有系统可以绑定到它。'],
        'BIND_DREAM_SERVICE': ['signature', '由DreamServices系统绑定所需。', '必须由DreamService要求，以确保只有系统可以绑定到它。'],
        'BIND_INCALL_SERVICE': ['signature', '由InCallServices系统绑定所需。', '必须由InCallService要求，以确保只有系统可以绑定到它。'],
        'BIND_MIDI_DEVICE_SERVICE': ['signature', '由MidiDeviceServices系统绑定所需。', '必须由MidiDeviceService要求，以确保只有系统可以绑定到它。'],
        'BIND_NFC_SERVICE': ['signature', '系统绑定到NFC服务所需的权限。', '必须由HostApduService或OffHostApduService要求，以确保只有系统可以绑定到它。'],
        'BIND_NOTIFICATION_LISTENER_SERVICE': ['signature', '由NotificationListenerServices系统绑定所需。', '必须由NotificationListenerService要求，以确保只有系统可以绑定到它。'],
        'BIND_PRINT_SERVICE': ['signature', '由PrintServices系统绑定所需。', '必须由PrintService要求，以确保只有系统可以绑定到它。'],
        'BIND_QUICK_SETTINGS_TILE': ['signatureOrSystem', '允许绑定到第三方快捷设置磁贴。', '允许应用绑定到第三方快捷设置磁贴。'],
        'BIND_REMOTEVIEWS': ['signature', '由RemoteViewsServices系统绑定所需。', '必须由RemoteViewsService要求，以确保只有系统可以绑定到它。'],
        'BIND_SCREENING_SERVICE': ['signature', '由CallScreeningServices系统绑定所需。', '必须由CallScreeningService要求，以确保只有系统可以绑定到它。'],
        'BIND_TELECOM_CONNECTION_SERVICE': ['signature', '由ConnectionServices系统绑定所需。', '必须由ConnectionService要求，以确保只有系统可以绑定到它。'],
        'BIND_TEXT_SERVICE': ['signature', '由TextServices(如SpellCheckerService)系统绑定所需。', '必须由TextService(如SpellCheckerService)要求，以确保只有系统可以绑定到它。'],
        'BIND_TV_INPUT': ['signature', '由TvInputServices系统绑定所需。', '必须由TvInputService要求，以确保只有系统可以绑定到它。'],
        'BIND_VISUAL_VOICEMAIL_SERVICE': ['signature', '由VisualVoicemailServices系统绑定所需。', '必须由VisualVoicemailService要求，以确保只有系统可以绑定到它。'],
        'BIND_VOICE_INTERACTION': ['signature', '由VoiceInteractionServices系统绑定所需。', '必须由VoiceInteractionService要求，以确保只有系统可以绑定到它。'],
        'BIND_VPN_SERVICE': ['signature', '由VpnServices系统绑定所需。', '必须由VpnService要求，以确保只有系统可以绑定到它。'],
        'BIND_VR_LISTENER_SERVICE': ['signature', '由VrListenerServices系统绑定所需。', '必须由VrListenerService要求，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_PRIVILEGED': ['signatureOrSystem', '允许在无用户交互的情况下进行特权蓝牙操作。', '允许应用在无用户交互的情况下配对蓝牙设备，并允许或禁止访问电话簿或消息。这不适用于第三方应用。'],
        'BODY_SENSORS': ['dangerous', '授予对身体传感器(如心率)的访问权限。', '允许应用访问用户用于测量身体内部情况的传感器数据，如心率。'],
        'CAPTURE_AUDIO_OUTPUT': ['signatureOrSystem', '允许捕获音频输出。', '允许应用捕获音频输出。'],
        'CAPTURE_SECURE_VIDEO_OUTPUT': ['normal', '允许捕获安全视频输出。', '允许应用捕获安全视频输出。'],
        'CAPTURE_VIDEO_OUTPUT': ['normal', '允许捕获视频输出。', '允许应用捕获视频输出。'],
        'FOREGROUND_SERVICE': ['normal', '允许常规应用使用Service.startForeground。', '允许常规应用使用Service.startForeground。'],
        'GET_ACCOUNTS_PRIVILEGED': ['signatureOrSystem', '授予对帐户服务的访问权限。', '允许访问帐户服务中的帐户列表。'],
        'INSTALL_SHORTCUT': ['normal', '允许在启动器中安装快捷方式。', '允许应用在启动器中安装快捷方式。'],
        'INSTANT_APP_FOREGROUND_SERVICE': ['signatureOrSystem', '允许即时应用创建前台服务。', '允许即时应用创建前台服务。'],
        'LOCATION_HARDWARE': ['normal', '允许使用硬件中的位置功能。', '允许应用使用硬件中的位置功能，如地理围栏API。'],
        'MANAGE_DOCUMENTS': ['signature', '允许管理文档访问，通常在选择器中。', '允许应用管理对文档的访问，通常作为文档选择器的一部分。'],
        'MANAGE_OWN_CALLS': ['normal', '允许调用应用管理其自己的通话。', '允许调用应用通过自管理的ConnectionService API管理其自己的通话。'],
        'MEDIA_CONTENT_CONTROL': ['normal', '允许控制媒体内容播放。', '允许应用了解正在播放的内容并控制其播放。'],
        'NFC_TRANSACTION_EVENT': ['normal', '允许接收NFC交易事件。', '允许应用接收NFC交易事件。'],
        'READ_CALL_LOG': ['dangerous', "授予读取用户通话记录的权限。", "允许应用读取用户的通话记录。"],
        'READ_PHONE_NUMBERS': ['dangerous', "允许读取设备的电话号码。", "允许读取设备的电话号码。这是READ_PHONE_STATE授予功能的一个子集，但向即时应用公开。"],
        'READ_VOICEMAIL': ['signature', '允许应用读取系统中的语音邮件。', '允许应用读取系统中的语音邮件。'],
        'REQUEST_COMPANION_RUN_IN_BACKGROUND': ['normal', '允许伴侣应用在后台运行。', '允许伴侣应用在后台运行。'],
        'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': ['normal', '允许伴侣应用在后台使用数据。', '允许伴侣应用在后台使用数据。'],
        'REQUEST_DELETE_PACKAGES': ['normal', '允许应用请求删除包。', '允许应用请求删除包。'],
        'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal', '用于Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS的权限。', '应用必须持有此权限才能使用Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS。'],
        'SEND_RESPOND_VIA_MESSAGE': ['signatureOrSystem', '允许在通话期间发送通过消息响应的请求。', '允许应用(电话)在来电时发送请求给其他应用，以处理通过消息响应的操作。'],
        'TRANSMIT_IR': ['normal', "允许使用设备的红外线发射器。", "允许使用设备的红外线发射器(如果有)。"],
        'UNINSTALL_SHORTCUT': ['normal', '卸载快捷方式的已废弃权限。', "不要在应用中使用此权限。此权限不再受支持。"],
        'USE_BIOMETRIC': ['normal', '允许使用设备支持的生物识别模式。', '允许应用使用设备支持的生物识别模式。'],
        'USE_FINGERPRINT': ['normal', '允许使用指纹。', '此常量在API级别28中已弃用。应用应请求USE_BIOMETRIC而不是此权限。'],
        'WRITE_CALL_LOG': ['dangerous', "允许写入(但不读取)用户的通话记录。", "允许应用写入(但不读取)用户的通话记录数据。"],
        'WRITE_VOICEMAIL': ['signature', '允许修改和删除语音邮件。', '允许应用修改和删除系统中现有的语音邮件。'],
        'ACCESS_BACKGROUND_LOCATION': ['dangerous', '在后台访问位置。', '允许应用在后台访问位置。'],
        'ACCESS_MEDIA_LOCATION': ['dangerous', '访问任何地理位置。', "允许应用访问用户共享集合中持久化的任何地理位置。"],
        'ACTIVITY_RECOGNITION': ['dangerous', '允许应用识别物理活动。', '允许应用识别物理活动。'],
        'BIND_CALL_REDIRECTION_SERVICE': ['signature', '由CallRedirectionServices系统绑定所需。', '必须由CallRedirectionService要求，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_CLIENT_SERVICE': ['signature', '由CarrierMessagingClientServices系统保护所需。', 'CarrierMessagingClientService的子类必须使用此权限保护。'],
        'CALL_COMPANION_APP': ['normal', '使InCallService应用作为通话伴侣功能。', "允许实现InCallService API的应用有资格作为通话伴侣应用启用。这意味着在有活动通话时，Telecom框架将绑定到应用的InCallService实现。应用可以使用InCallService API查看系统上通话的信息并控制这些通话。"],
        'REQUEST_PASSWORD_COMPLEXITY': ['normal', '允许请求和提示屏幕锁复杂度升级。', '允许应用请求屏幕锁复杂度并提示用户将屏幕锁更新到某个复杂度级别。'],
        'SMS_FINANCIAL_TRANSACTIONS': ['signature', '允许金融应用读取过滤的短信消息。', '允许金融应用读取过滤的短信消息。保护级别：signature|appop。此常量在API级别S中已弃用。'],
        'START_VIEW_PERMISSION_USAGE': ['signature', '允许启动权限使用屏幕。', '允许持有者启动权限使用屏幕。'],
        'USE_FULL_SCREEN_INTENT': ['normal', '通知中全屏意图所需。', '目标为Build.VERSION_CODES.Q的应用在通知中使用全屏意图时需要此权限。'],
        'ACCESS_CALL_AUDIO': ['signature', '应用可以访问通话音频。', '允许分配给拨号角色的应用访问电话通话音频流，包括TX和RX。'],
        'BIND_CONTROLS': ['signatureOrSystem', '允许SystemUI请求第三方控件。', '允许SystemUI请求第三方控件。仅系统和ControlsProviderService声明所需。'],
        'BIND_QUICK_ACCESS_WALLET_SERVICE': ['signature', '由QuickAccessWalletServices系统绑定所需。', '必须由QuickAccessWalletService要求，以确保只有系统可以绑定到它。'],
        'INTERACT_ACROSS_PROFILES': ['normal', '允许在同一组配置文件中的交互。', '允许在同一组配置文件中的交互。'],
        'LOADER_USAGE_STATS': ['signatureOrSystem', '允许数据加载器读取包访问日志。', "允许数据加载器读取包的访问日志。访问日志包含随时间引用的页面集。"],
        'MANAGE_EXTERNAL_STORAGE': ['dangerous', '允许应用在范围存储中广泛访问外部存储。', '允许应用在范围存储中广泛访问外部存储。旨在为需要代表用户管理文件的少数应用使用。'],
        'NFC_PREFERRED_PAYMENT_INFO': ['normal', '允许接收NFC首选支付服务信息。', '允许应用接收NFC首选支付服务信息。'],
        'QUERY_ALL_PACKAGES': ['normal', '允许查询设备上的任何正常应用。', '允许查询设备上的任何正常应用，无论清单声明如何。'],
        'READ_PRECISE_PHONE_STATE': ['dangerous', '允许只读访问精确的电话状态。', '允许只读访问精确的电话状态。允许读取有关电话状态的详细信息，适用于特殊用途的应用如拨号器、运营商应用或IMS应用。'],
        'READ_APP_BADGE': ['normal', '显示应用通知。', '允许应用显示应用图标徽章。'],
        'BIND_COMPANION_DEVICE_SERVICE': ['normal', '由CompanionDeviceServices系统绑定所需。', 'CompanionDeviceServices必须要求此权限，以确保只有系统可以绑定到它。'],
        'HIDE_OVERLAY_WINDOWS': ['normal', '防止非系统覆盖窗口。', '允许应用防止非系统覆盖窗口在其上方绘制。'],
        'HIGH_SAMPLING_RATE_SENSORS': ['normal', '访问更高采样率的传感器数据。', '允许应用访问采样率超过200 Hz的传感器数据。'],
        'MANAGE_ONGOING_CALLS': ['signature', '查询和管理正在进行的通话详情。', '允许查询正在进行的通话详情并管理正在进行的通话。'],
        'REQUEST_COMPANION_PROFILE_WATCH': ['normal', "允许与设备作为'手表'关联。", '允许应用请求通过CompanionDeviceManager与设备关联作为“手表”。'],
        'REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE': ['normal', '允许订阅伴侣设备状态通知。', '允许应用订阅其关联的伴侣设备状态变化的通知。'],
        'SCHEDULE_EXACT_ALARM': ['normal', '允许为后台工作安排精确的闹钟。', '允许应用使用精确闹钟调度API来执行对时间敏感的后台工作。'],
        'USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER': ['signature', '允许读取设备标识符并使用ICC基于的认证。', "允许读取设备标识符并使用ICC基于的认证，如EAP-AKA。通常在认证访问运营商服务器和管理订阅者服务时需要。"],
        'ACCESS_BLOBS_ACROSS_USERS': ['normal', '允许跨用户访问数据块。', '允许应用跨用户访问数据块。'],
        'BIND_CREDENTIAL_PROVIDER_SERVICE': ['signature', '由CredentialProviderServices系统绑定所需。', '必须由CredentialProviderService要求，以确保只有系统可以绑定到它。'],
        'BIND_TV_INTERACTIVE_APP': ['signature', '由TvInteractiveAppServices系统绑定所需。', '必须由TvInteractiveAppService要求，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_ADVERTISE': ['dangerous', '需要广告发布到附近的蓝牙设备。', '需要广告发布到附近的蓝牙设备。'],
        'BLUETOOTH_CONNECT': ['dangerous', '连接到已配对的蓝牙设备所需。', '需要连接到已配对的蓝牙设备。'],
        'BLUETOOTH_SCAN': ['dangerous', '发现和配对蓝牙设备所需。', '需要发现和配对附近的蓝牙设备。'],
        'BODY_SENSORS_BACKGROUND': ['dangerous', '允许后台访问身体传感器数据，如心率。', "允许应用后台访问用户用于测量身体内部情况的传感器数据，如心率。如果请求此权限，必须同时请求BODY_SENSORS。仅请求此权限并不会授予身体传感器访问权限。"],
        'CONFIGURE_WIFI_DISPLAY': ['normal', '允许配置和连接到WiFi显示器。', '允许应用配置和连接到WiFi显示器。'],
        'CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS': ['normal', '允许查询凭证候选人的元数据。', '允许浏览器调用查询API以获取在CredentialManager.prepareGetCredential API期间准备的凭证候选人的元数据。'],
        'CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS': ['normal', '允许指定候选凭证提供者。', '允许指定候选凭证提供者在Credential Manager获取流中被查询，或在Credential Manager创建流中被优先作为默认值。'],
        'CREDENTIAL_MANAGER_SET_ORIGIN': ['normal', '允许代表另一个RP调用凭证管理器API。', '允许浏览器代表另一个RP调用凭证管理器API。'],
        'DELIVER_COMPANION_MESSAGES': ['normal', '允许向系统传递伴侣消息。', '允许应用向系统传递伴侣消息。'],
        'DETECT_SCREEN_CAPTURE': ['normal', "在尝试截屏时通知。", '允许应用在尝试截屏其窗口时收到通知。'],
        'ENFORCE_UPDATE_OWNERSHIP': ['normal', '表示意图通过PackageInstaller成为更新所有者。', '允许应用通过PackageInstaller.SessionParams.setRequestUpdateOwnership(boolean)表示其有意成为更新所有者。'],
        'EXECUTE_APP_ACTION': ['internal', '允许辅助应用在其他应用内执行操作。', '允许辅助应用代表用户在应用内执行操作。'],
        'FOREGROUND_SERVICE_CAMERA': ['normal', '允许前台服务使用相机。', '允许常规应用使用Service.startForeground并指定类型为“相机”。'],
        'FOREGROUND_SERVICE_CONNECTED_DEVICE': ['normal', '允许前台服务使用已连接设备。', '允许常规应用使用Service.startForeground并指定类型为“已连接设备”。'],
        'FOREGROUND_SERVICE_DATA_SYNC': ['normal', '允许前台服务进行数据同步。', '允许常规应用使用Service.startForeground并指定类型为“数据同步”。'],
        'FOREGROUND_SERVICE_HEALTH': ['normal', '允许前台服务使用与健康相关的功能。', '允许常规应用使用Service.startForeground并指定类型为“健康”。'],
        'FOREGROUND_SERVICE_LOCATION': ['normal', '允许前台服务使用位置。', '允许常规应用使用Service.startForeground并指定类型为“位置”。'],
        'FOREGROUND_SERVICE_MEDIA_PLAYBACK': ['normal', '允许前台服务进行媒体播放。', '允许常规应用使用Service.startForeground并指定类型为“媒体播放”。'],
        'FOREGROUND_SERVICE_MEDIA_PROJECTION': ['normal', '允许前台服务进行媒体投影。', '允许常规应用使用Service.startForeground并指定类型为“媒体投影”。'],
        'FOREGROUND_SERVICE_MICROPHONE': ['normal', '允许前台服务使用麦克风。', '允许常规应用使用Service.startForeground并指定类型为“麦克风”。'],
        'FOREGROUND_SERVICE_PHONE_CALL': ['normal', '允许前台服务在通话期间使用。', '允许常规应用使用Service.startForeground并指定类型为“电话呼叫”。'],
        'FOREGROUND_SERVICE_REMOTE_MESSAGING': ['normal', '允许前台服务进行远程消息传递。', '允许常规应用使用Service.startForeground并指定类型为“远程消息传递”。'],
        'FOREGROUND_SERVICE_SPECIAL_USE': ['normal', '允许前台服务进行特殊用途。', '允许常规应用使用Service.startForeground并指定类型为“特殊用途”。'],
        'FOREGROUND_SERVICE_SYSTEM_EXEMPTED': ['normal', '允许系统豁免类型的前台服务。', '允许常规应用使用Service.startForeground并指定类型为“系统豁免”。仅允许在ServiceInfo.FOREGROUND_SERVICE_TYPE_SYSTEM_EXEMPTED中列出的用例中使用此类型。'],
        'LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE': ['internal', '允许截屏以执行截图。', '允许应用通过Intent.ACTION_LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE意图操作截屏以执行截图。'],
        'LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK': ['normal', '允许在设置应用中嵌入显示活动。', '应用需要此权限才能通过Settings.ACTION_SETTINGS_EMBED_DEEP_LINK_ACTIVITY在设置应用中显示其活动。'],
        'MANAGE_DEVICE_LOCK_STATE': ['internal', '允许融资设备亭应用与设备锁服务交互。', '允许融资设备亭应用对设备锁服务执行操作。'],
        'MANAGE_DEVICE_POLICY_ACCESSIBILITY': ['normal', '允许管理与无障碍相关的政策。', '允许应用管理与无障碍相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT': ['normal', '允许设置与帐户管理相关的政策。', '允许应用设置与帐户管理相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS': ['normal', '允许在不访问用户数据的情况下设置安全设备政策。', '允许应用在当前用户之外设置所需的设备政策，以确保设备所有权的安全而不访问用户数据。持有此权限允许在设备上的所有用户中使用其他持有的MANAGE_DEVICE_POLICY_*权限，前提是不授予访问用户数据的权限。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL': ['normal', '允许访问用户数据时设置设备政策。', '允许应用在当前用户之外设置设备政策。MANAGE_DEVICE_POLICY_ACROSS_USERS的更全面形式，去除了访问用户数据的限制。持有此权限允许在设备上的所有用户中使用其他持有的MANAGE_DEVICE_POLICY_*权限。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL': ['normal', '允许设置保护用户数据安全的关键安全政策。', '允许应用在当前用户之外设置保护当前用户数据安全的关键政策。持有此权限允许在设备上的所有用户中使用其他持有的MANAGE_DEVICE_POLICY_*权限，前提是它们需要保护当前用户的数据。'],
        'MANAGE_DEVICE_POLICY_AIRPLANE_MODE': ['normal', '允许设置与飞行模式相关的政策。', '允许应用设置与飞行模式相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_APPS_CONTROL': ['normal', '允许管理修改应用的政策。', '允许应用管理与修改应用相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_APP_RESTRICTIONS': ['normal', '允许管理应用限制的政策。', '允许应用管理应用限制。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_APP_USER_DATA': ['normal', '允许设置应用用户数据的政策。', '允许应用管理与应用用户数据相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_AUDIO_OUTPUT': ['normal', '允许设置音频输出的政策。', '允许应用设置与音频输出相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_AUTOFILL': ['normal', '允许设置自动填充服务的政策。', '允许应用设置与自动填充相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_BACKUP_SERVICE': ['normal', '允许管理备份服务政策。', '允许应用管理备份服务政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_BLUETOOTH': ['normal', '允许设置与蓝牙相关的政策。', '允许应用设置与蓝牙相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_BUGREPORT': ['normal', '允许在用户同意的情况下请求bug报告。', '允许应用在用户同意的情况下请求bug报告。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_CALLS': ['normal', '允许管理电话通话的政策。', '允许应用管理电话通话的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_CAMERA': ['normal', '允许设置相机使用的政策。', "允许应用设置与限制用户使用或启用和禁用相机相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。"],
        'MANAGE_DEVICE_POLICY_CERTIFICATES': ['normal', '允许管理证书的政策。', '允许应用设置与证书相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE': ['normal', '允许管理通用标准模式的政策。', '允许应用管理与通用标准模式相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES': ['normal', '允许管理调试功能的政策。', '允许应用管理调试功能政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_DEFAULT_SMS': ['normal', '允许设置默认SMS应用的政策。', '允许应用设置与默认SMS应用相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS': ['normal', '允许管理设备标识符的政策。', '允许应用管理与设备标识符相关的政策。'],
        'MANAGE_DEVICE_POLICY_DISPLAY': ['normal', '允许设置显示管理的政策。', '允许应用设置与显示相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_FACTORY_RESET': ['normal', '允许设置恢复出厂设置的政策。', '允许应用设置与恢复出厂设置相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_FUN': ['normal', '允许设置与娱乐活动相关的政策。', '允许应用设置与娱乐相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_INPUT_METHODS': ['normal', '允许设置输入法的政策。', '允许应用设置与输入法相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES': ['normal', '允许管理从未知来源安装应用的政策。', '允许应用管理从未知来源安装应用的政策。需要MANAGE_SECURITY_CRITICAL_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES': ['normal', '允许根据政策保留已卸载的包。', '允许应用设置与保留已卸载包相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_KEYGUARD': ['normal', '允许管理锁屏设置的政策。', '允许应用管理与锁屏相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_LOCALE': ['normal', '允许设置语言管理的政策。', '允许应用设置与语言相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_LOCATION': ['normal', '允许设置位置服务的政策。', '允许应用设置与位置相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_LOCK': ['normal', '允许根据政策锁定配置文件或设备。', '允许应用根据适当的跨用户权限锁定配置文件或设备。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS': ['normal', '允许设置锁定凭据的政策。', '允许应用设置与锁定凭据相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_LOCK_TASK': ['normal', '允许管理锁定任务的政策。', '允许应用管理锁定任务的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_METERED_DATA': ['normal', '允许管理计量数据的政策。', '允许应用管理与计量数据相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE': ['normal', '允许设置麦克风使用的政策。', "允许应用设置与限制用户使用或启用和禁用麦克风相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。"],
        'MANAGE_DEVICE_POLICY_MOBILE_NETWORK': ['normal', '允许设置移动网络的政策。', '允许应用设置与移动网络相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_MODIFY_USERS': ['normal', '允许管理防止用户修改的政策。', '允许应用管理防止用户修改用户的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_MTE': ['normal', '允许管理内存标记扩展(MTE)的政策。', '允许应用管理与内存标记扩展(MTE)相关的政策。'],
        'MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION': ['normal', '允许设置附近通信的政策。', '允许应用设置与附近通信(如Beam和附近流)相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_NETWORK_LOGGING': ['normal', '允许设置网络日志记录的政策。', '允许应用设置与网络日志记录相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY': ['normal', '允许管理管理组织的身份。', '允许应用管理管理组织的身份。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_OVERRIDE_APN': ['normal', '允许设置覆盖APN的政策。', '允许应用设置与覆盖APN相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PACKAGE_STATE': ['normal', '允许隐藏和暂停包的政策。', '允许应用设置与隐藏和暂停包相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA': ['normal', '允许设置物理媒体使用的政策。', '允许应用设置与物理媒体相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PRINTING': ['normal', '允许设置打印服务的政策。', '允许应用设置与打印相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PRIVATE_DNS': ['normal', '允许设置私有DNS管理的政策。', '允许应用设置与私有DNS相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PROFILES': ['normal', '允许设置用户配置文件的政策。', '允许应用设置与配置文件相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PROFILE_INTERACTION': ['normal', '允许设置用户配置文件之间交互的政策。', '允许应用设置与配置文件交互(如禁止跨配置文件复制和粘贴)相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_PROXY': ['normal', '允许设置独立于网络的全局HTTP代理。', '允许应用设置独立于网络的全局HTTP代理。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES': ['normal', '允许查询系统更新。', '允许应用查询系统更新。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_RESET_PASSWORD': ['normal', '允许强制设置新设备解锁密码或配置文件挑战。', '允许应用在当前用户上强制设置新的设备解锁密码或管理配置文件挑战。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS': ['normal', '允许限制用户配置私有DNS。', '允许应用设置限制用户配置私有DNS的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS': ['normal', '允许设置包的运行时权限。', '允许应用设置包的运行时权限授予状态。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND': ['normal', '允许设置后台进程管理的政策。', '允许应用设置与用户在后台运行相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SAFE_BOOT': ['normal', '允许管理安全启动模式的政策。', '允许应用管理安全启动政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CAPTURE': ['normal', '允许设置屏幕捕获功能的政策。', '允许应用设置与屏幕捕获相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CONTENT': ['normal', '允许设置屏幕内容使用的政策。', '允许应用设置与屏幕内容使用相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SECURITY_LOGGING': ['normal', '允许设置安全日志记录的政策。', '允许应用设置与安全日志记录相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SETTINGS': ['normal', '允许设置常规设备政策。', '允许应用设置与设置相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SMS': ['normal', '允许设置SMS功能的政策。', '允许应用设置与SMS相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_STATUS_BAR': ['normal', '允许设置状态栏的政策。', '允许应用设置与状态栏相关的政策。'],
        'MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE': ['normal', '允许为受政策影响的操作设置支持消息。', '允许应用设置在用户操作受到活动政策影响时的支持消息。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS': ['normal', '允许通过政策设置暂停个人应用。', '允许应用设置与暂停个人应用相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_APPS': ['normal', '允许管理与系统应用相关的政策。', '允许应用管理与系统应用相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS': ['normal', '允许设置系统对话框的政策。', '允许应用设置与系统对话框相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_UPDATES': ['normal', '允许设置系统更新的政策。', '允许应用设置与系统更新相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_TIME': ['normal', '允许管理与时间设置相关的政策。', '允许应用管理与时间相关的设备政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING': ['normal', '允许设置USB数据信号的政策。', '允许应用设置与USB数据信号相关的政策。'],
        'MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER': ['normal', '允许设置USB文件传输的政策。', '允许应用设置与USB文件传输相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_USERS': ['normal', '允许设置与用户管理相关的政策。', '允许应用设置与用户相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_VPN': ['normal', '允许设置VPN使用的政策。', '允许应用设置与VPN相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_WALLPAPER': ['normal', '允许设置壁纸管理的政策。', '允许应用设置与壁纸相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_WIFI': ['normal', '允许设置WiFi连接的政策。', '允许应用设置与WiFi相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_WINDOWS': ['normal', '允许设置窗口管理的政策。', '允许应用设置与窗口相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL才能调用受此权限保护的API。'],
        'MANAGE_DEVICE_POLICY_WIPE_DATA': ['normal', '允许管理与数据擦除相关的政策。', '允许应用管理与数据擦除相关的政策。需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS才能调用受此权限保护的API。'],
        'MANAGE_MEDIA': ['signature', '允许修改和删除媒体文件，无需用户确认。', '允许应用修改和删除设备或任何连接存储设备上的媒体文件，无需用户确认。应用必须已经授予READ_EXTERNAL_STORAGE或MANAGE_EXTERNAL_STORAGE权限，才能使此权限生效。'],
        'MANAGE_WIFI_INTERFACES': ['normal', '允许管理Wi-Fi接口请求之间的冲突。', '允许应用在Wi-Fi接口请求无法满足而不拆除一个或多个其他接口时收到通知，并提供批准或拒绝请求的决策。不适用于第三方应用。'],
        'MANAGE_WIFI_NETWORK_SELECTION': ['normal', '允许特权管理Wi-Fi网络选择。', '此权限用于允许OEM授予其受信任的应用访问子集特权wifi API以改进wifi性能。允许应用管理与Wi-Fi网络选择相关的功能，如启用或禁用全局自动加入、修改连接扫描间隔以及批准Wi-Fi Direct连接。不适用于第三方应用。'],
        'NEARBY_WIFI_DEVICES': ['dangerous', '需要广告发布和连接到附近设备的Wi-Fi。', '需要能够通过Wi-Fi广告发布和连接到附近设备。'],
        'OVERRIDE_WIFI_CONFIG': ['normal', '允许修改任何Wi-Fi配置。', '允许应用修改任何Wi-Fi配置，即使是由其他应用创建的。一旦重新配置，原始创建者无法进行任何进一步的修改。不适用于第三方应用。'],
        'POST_NOTIFICATIONS': ['dangerous', '允许应用发布通知。', '允许应用发布通知。'],
        'PROVIDE_OWN_AUTOFILL_SUGGESTIONS': ['internal', '允许使用自动填充框架提供自动填充建议。', '允许应用使用自动填充框架显示其建议。'],
        'PROVIDE_REMOTE_CREDENTIALS': ['signature', '允许存储和检索远程设备上的凭证。', '允许应用能够存储和检索远程设备上的凭证。'],
        'READ_ASSISTANT_APP_SEARCH_DATA': ['normal', '允许查询可见于助手角色的全局AppSearch数据。', "允许应用查询助手角色可见的全局AppSearch数据。"],
        'READ_BASIC_PHONE_STATE': ['normal', '允许只读访问基本电话状态信息。', '允许只读访问基本电话状态，包括蜂窝网络类型、软件版本等信息。'],
        'READ_HOME_APP_SEARCH_DATA': ['normal', '允许查询可见于主页角色的全局AppSearch数据。', "允许应用查询主页角色可见的全局AppSearch数据。"],
        'READ_MEDIA_AUDIO': ['dangerous', '允许从外部存储读取音频文件。', '允许应用从外部存储读取音频文件。'],
        'READ_MEDIA_IMAGES': ['dangerous', '允许从外部存储读取图像文件。', '允许应用从外部存储读取图像文件。'],
        'READ_MEDIA_VIDEO': ['dangerous', '允许从外部存储读取视频文件。', '允许应用从外部存储读取视频文件。'],
        'READ_MEDIA_VISUAL_USER_SELECTED': ['dangerous', '允许从外部存储读取用户选择的图像或视频文件。', '允许应用从外部存储读取用户通过权限提示照片选择器选择的图像或视频文件。应用可以检查此权限，以验证用户已决定使用照片选择器，而不是授予访问READ_MEDIA_IMAGES或READ_MEDIA_VIDEO的权限。它不会阻止应用手动访问标准照片选择器。应根据所需的媒体类型，请求此权限与READ_MEDIA_IMAGES和/或READ_MEDIA_VIDEO一起请求。'],
        'READ_NEARBY_STREAMING_POLICY': ['normal', '允许读取附近流策略设置。', '允许应用读取附近流策略。策略控制是否允许设备将其通知和应用流传输到附近设备。不是设备所有者的应用需要此权限才能调用DevicePolicyManager.getNearbyNotificationStreamingPolicy()或DevicePolicyManager.getNearbyAppStreamingPolicy()。'],
        'REQUEST_COMPANION_PROFILE_APP_STREAMING': ['normal', '允许请求与用于应用流传输的虚拟显示关联。', '允许应用请求通过CompanionDeviceManager与能够流传输Android应用的虚拟显示关联(AssociationRequest.DEVICE_PROFILE_APP_STREAMING)。不适用于第三方应用。'],
        'REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION': ['normal', '允许请求与用于汽车投影的车载单元关联。', '允许应用请求通过CompanionDeviceManager与能够进行汽车投影的车载单元关联(AssociationRequest.DEVICE_PROFILE_AUTOMOTIVE_PROJECTION)。不适用于第三方应用。'],
        'REQUEST_COMPANION_PROFILE_COMPUTER': ['normal', '允许请求与计算机关联以共享功能。', '允许应用请求通过CompanionDeviceManager与计算机关联以共享功能和/或数据，如通知、照片和媒体(AssociationRequest.DEVICE_PROFILE_COMPUTER)。不适用于第三方应用。'],
        'REQUEST_COMPANION_PROFILE_GLASSES': ['normal', "允许请求与设备作为'眼镜'关联。", '允许应用请求通过CompanionDeviceManager与设备关联作为“眼镜”'],
        'REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING': ['normal', '允许请求向附近设备流传输内容。', '允许应用通过CompanionDeviceManager请求从Android主机向附近设备流传输内容(AssociationRequest.DEVICE_PROFILE_NEARBY_DEVICE_STREAMING)。不适用于第三方应用。'],
        'REQUEST_COMPANION_SELF_MANAGED': ['normal', '允许创建自管理的伴侣设备关联。', '允许应用创建“自管理”关联。'],
        'REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许伴侣应用从后台启动前台服务。', '允许伴侣应用从后台启动前台服务。'],
        'RUN_USER_INITIATED_JOBS': ['normal', '允许使用用户发起的作业API。', '允许应用使用用户发起的作业API。有关更多详细信息，请参阅JobInfo.Builder.setUserInitiated(boolean)。'],
        'START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许从后台启动前台服务。', "允许应用随时从后台启动前台服务。此权限不适用于第三方应用，唯一的例外是如果应用是默认的SMS应用。否则，它仅适用于特权应用、应用验证器应用以及具有任何紧急或系统图库角色的应用。"],
        'START_VIEW_APP_FEATURES': ['signature', '允许启动显示应用功能的屏幕。', '允许持有者启动显示应用功能的屏幕。'],
        'SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE': ['signature', '允许订阅锁屏状态。', '允许应用订阅锁屏(即显示)状态。'],
        'TURN_SCREEN_ON': ['normal', '允许家庭自动化应用打开屏幕。', '允许应用打开屏幕，例如使用PowerManager.ACQUIRE_CAUSES_WAKEUP。仅用于家庭自动化应用。'],
        'UPDATE_PACKAGES_WITHOUT_USER_ACTION': ['normal', '允许在不需要用户操作的情况下更新包。', '允许应用通过PackageInstaller.SessionParams.setRequireUserAction(int)指示不需要用户操作的应用更新。'],
        'USE_EXACT_ALARM': ['normal', '允许在无用户权限的情况下使用精确闹钟。', '允许应用使用精确闹钟，就像使用SCHEDULE_EXACT_ALARM一样，但无需请求用户权限。仅用于依赖精确闹钟作为核心功能的应用。如果您的应用需要精确闹钟作为次要功能，请继续使用SCHEDULE_EXACT_ALARM。请记住，这是一个强大的权限，应用商店可能会审核和检查此权限的使用。如果发现应用滥用此权限，可能会将其从应用商店中删除。'],
        'UWB_RANGING': ['dangerous', '需要使用超宽带设备测距。', '需要能够使用超宽带测距设备。'],

    },

    'SPECIAL_PERMISSIONS': {
        'com.sec.android.provider.badge.permission.READ': ['normal', '显示应用上的通知计数', '在三星手机的应用启动图标上显示通知计数或徽章。'],
        'com.sec.android.provider.badge.permission.WRITE': ['normal', '显示应用上的通知计数', '在三星手机的应用启动图标上显示通知计数或徽章。'],
        'com.htc.launcher.permission.READ_SETTINGS': ['normal', '显示应用上的通知计数', '在HTC手机的应用启动图标上显示通知计数或徽章。'],
        'com.htc.launcher.permission.UPDATE_SHORTCUT': ['normal', '显示应用上的通知计数', '在HTC手机的应用启动图标上显示通知计数或徽章。'],
        'com.sonyericsson.home.permission.BROADCAST_BADGE': ['normal', '显示应用上的通知计数', '在索尼手机的应用启动图标上显示通知计数或徽章。'],
        'com.sonymobile.home.permission.PROVIDER_INSERT_BADGE': ['normal', '显示应用上的通知计数', '在索尼手机的应用启动图标上显示通知计数或徽章。'],
        'com.anddoes.launcher.permission.UPDATE_COUNT': ['normal', '显示应用上的通知计数', '在Apex启动器的应用启动图标上显示通知计数或徽章。'],
        'com.majeur.launcher.permission.UPDATE_BADGE': ['normal', '显示应用上的通知计数', '在Solid启动器的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.READ_SETTINGS': ['normal', '显示应用上的通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.WRITE_SETTINGS': ['normal', '显示应用上的通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.CHANGE_BADGE': ['normal', '显示应用上的通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.oppo.launcher.permission.READ_SETTINGS': ['normal', '显示应用上的通知计数', '在OPPO手机的应用启动图标上显示通知计数或徽章。'],
        'com.oppo.launcher.permission.WRITE_SETTINGS': ['normal', '显示应用上的通知计数', '在OPPO手机的应用启动图标上显示通知计数或徽章。'],
        'com.google.android.gms.permission.AD_ID': ['normal', '应用显示广告', '该应用使用谷歌广告ID，并可能显示广告。'],
        'com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE': ['normal', '由谷歌定义的权限', '由谷歌定义的自定义权限。'],
        'com.google.android.c2dm.permission.RECEIVE': ['normal', '接收推送通知', '允许应用从云端接收推送通知。'],
        'com.android.vending.BILLING': ['normal', '应用内购买', '允许应用通过Google Play进行应用内购买。'],
        'android.permission.ACCESS_ADSERVICES_TOPICS': ['normal', '允许应用访问广告服务主题', '使应用能够检索与广告主题或兴趣相关的信息，可用于目标广告。'],
        'android.permission.ACCESS_ADSERVICES_ATTRIBUTION': ['normal', '允许应用访问广告服务归因', '使应用能够检索与广告归因相关的信息，可用于目标广告。应用可以收集有关用户与广告的互动数据(如点击或展示)，以衡量广告活动的有效性。'],
        'android.permission.ACCESS_ADSERVICES_AD_ID': ['normal', '允许应用访问设备的广告ID', '该ID是谷歌广告服务提供的唯一、可由用户重置的标识符，允许应用在保持用户隐私的同时追踪用户行为以用于广告目的。'],
        'oppo.permission.OPPO_COMPONENT_SAFE': ['signature', 'OPPO设备特定的权限', '用于授权应用访问因安全原因受限的某些系统级功能或组件。此权限确保只有受信任的应用才能与OPPO系统的敏感部分互动。'],
        'com.huawei.permission.external_app_settings.USE_COMPONENT': ['signature', '华为设备特定的权限', '用于授权应用访问因安全原因受限的某些系统级功能或组件。此权限确保只有受信任的应用才能与华为系统的敏感部分互动。']
    },


    'MANIFEST_PERMISSION_GROUP': {
        'ACCOUNTS': '直接访问由账户管理器管理的账户的权限。',
        'COST_MONEY': '用于可能使用户在不直接参与的情况下花费金钱的权限。',
        'DEVELOPMENT_TOOLS': '与开发功能相关的权限组。',
        'HARDWARE_CONTROLS': '用于提供对设备硬件直接访问的权限。',
        'LOCATION': '用于允许访问用户当前位置的权限。',
        'MESSAGES': '允许应用代表用户发送消息或拦截用户接收的消息的权限。',
        'NETWORK': '提供访问网络服务的权限。',
        'PERSONAL_INFO': '提供访问用户的私人数据的权限，如联系人、日历事件、电子邮件等。',
        'PHONE_CALLS': '与访问和修改电话状态相关的权限：拦截外呼电话、读取和修改电话状态。',
        'STORAGE': '与SD卡访问相关的权限组。',
        'SYSTEM_TOOLS': '与系统API相关的权限组。'
    },

}
