version: '3.8'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - /root/MobSF/postgresql_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
    ports:
      - "5432:5432"
    networks:
        - mobsf
      
  mobsf:
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
      - POSTGRES_HOST=postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - POSTGRES=True
    volumes:
      - /root/MobSF/mobsf_data:/home/mobsf/.MobSF
    ports:
     - "8000:8000"
    networks:
      - mobsf
    depends_on:
      - postgres
    links:
      - "postgres"
networks:
  mobsf:
